# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.5.5
group=org.dawnoftime.armoroftheages
java_version=21

# Common
minecraft_version=1.21.8
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.8
parchment_version=2025.09.14
# NeoForge

neoforge_version=21.8.47
neoforge_loader_version_range=[4,)
neo_form_version=1.21.8-20250717.133445

minecraft_version_range=[1.21.8]

# Fabric
fabric_version=0.133.4+1.21.8
fabric_loader_version=0.17.2

# Configuration
yacl_version=3.7.1+1.21.6

# Mod options
mod_name=Armor of the Ages
mod_author=Poulpinou
credits=TheGoldenWorld, Mr_ch0c0late, Hahdrim
mod_id=armoroftheages
license=MIT
description=A mod that adds fancy armors from different cultures.

# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false